In [53]:
import numpy as np
import pandas as pd


# EDA, cleaning

In [54]:
df = pd.read_csv('../LLCP2023.csv')
df

_STATE  FMONTH     IDATE  IMONTH  IDAY  IYEAR  DISPCODE       SEQNO  \
0          1.0     1.0   3012023       3     1   2023    1100.0  2023000001   
1          1.0     1.0   1062023       1     6   2023    1100.0  2023000002   
2          1.0     1.0   3082023       3     8   2023    1100.0  2023000003   
3          1.0     1.0   3062023       3     6   2023    1100.0  2023000004   
4          1.0     1.0   1062023       1     6   2023    1100.0  2023000005   
...        ...     ...       ...     ...   ...    ...       ...         ...   
433318    78.0    12.0  12112023      12    11   2023    1100.0  2023002064   
433319    78.0    12.0   1032024       1     3   2024    1100.0  2023002065   
433320    78.0    12.0  12132023      12    13   2023    1100.0  2023002066   
433321    78.0    12.0  12082023      12     8   2023    1100.0  2023002067   
433322    78.0    12.0  12112023      12    11   2023    1100.0  2023002068   

                _PSU  CTELENM1  ...      DROCDY4_  _RFBING6      _DRNKWK2  \
0       2.023000e+09       1.0  ...  5.397605e-79       1.0  5.397605e-79   
1       2.023000e+09       1.0  ...  5.397605e-79       1.0  5.397605e-79   
2       2.023000e+09       1.0  ...  5.397605e-79       1.0  5.397605e-79   
3       2.023000e+09       1.0  ...  5.397605e-79       1.0  5.397605e-79   
4       2.023000e+09       1.0  ...  7.000000e+00       1.0  4.700000e+01   
...              ...       ...  ...           ...       ...           ...   
433318  2.023002e+09       NaN  ...  7.100000e+01       2.0  1.500000e+03   
433319  2.023002e+09       NaN  ...  5.397605e-79       1.0  5.397605e-79   
433320  2.023002e+09       NaN  ...  3.000000e+00       1.0  4.700000e+01   
433321  2.023002e+09       NaN  ...  5.397605e-79       1.0  5.397605e-79   
433322  2.023002e+09       NaN  ...  6.700000e+01       2.0  9.330000e+02   

        _RFDRHV8  _FLSHOT7  _PNEUMO3  _AIDTST4  _RFSEAT2  _RFSEAT3  _DRNKDRV  
0            1.0       2.0       2.0       2.0       1.0       1.0       9.0  
1            1.0       1.0       1.0       2.0       1.0       1.0       9.0  
2            1.0       1.0       1.0       2.0       1.0       1.0       9.0  
3            1.0       1.0       1.0       1.0       1.0       1.0       9.0  
4            1.0       2.0       1.0       2.0       1.0       1.0       2.0  
...          ...       ...       ...       ...       ...       ...       ...  
433318       2.0       2.0       2.0       1.0       1.0       2.0       2.0  
433319       1.0       NaN       NaN       1.0       1.0       1.0       9.0  
433320       1.0       NaN       NaN       1.0       1.0       1.0       2.0  
433321       1.0       2.0       2.0       2.0       1.0       1.0       9.0  
433322       1.0       NaN       NaN       2.0       1.0       2.0       2.0  

[433323 rows x 350 columns]

In [55]:
df = df.loc[:,'_RFHLTH':] #only keep the 76 calculated variables

In [56]:
#choose columns relevant to the study
columns_to_keep = ['_RFHLTH', '_PHYS14D', '_MENT14D', '_HLTHPL1', '_TOTINDA','METVL12_','MAXVO21_', 'FC601_','ACTIN13_','PADUR1_' ,'PAFREQ1_','_MINAC12','STRFREQ_','PAVIG13_', 'PA3MIN_','_PACAT3','_PAINDX3','_PA150R4', '_PA300R4', '_PA30023', '_PASTRNG', '_PAREC3', '_PASTAE3', '_RFHYPE6', '_CHOLCH3', '_RFCHOL3', '_MICHD', '_LTASTH1', '_CASTHM1', '_ASTHMS1', '_DRDXAR2', '_SEX', '_AGE80',   '_BMI5', '_RFBMI5', '_INCOMG1','_RACE', '_EDUCAG','_SMOKER3', '_RFSMOK3', '_CURECI2', 'DROCDY4_', '_RFBING6', '_RFSEAT2','_DRNKWK2']
df_filter = df[columns_to_keep]

missing_9_columns = ['_RFHLTH', '_PHYS14D', '_MENT14D', '_HLTHPL1', '_TOTINDA', '_PACAT3', '_PA150R4', '_PA300R4', '_PA30023', '_PASTRNG', '_PAREC3', '_PASTAE3', '_RFHYPE6', '_CHOLCH3', '_RFCHOL3', '_LTASTH1', '_CASTHM1', '_ASTHMS1', '_RFBMI5', '_RACE', '_SMOKER3', '_RFSMOK3', '_CURECI2', '_RFBING6','_PAINDX3','_EDUCAG','_INCOMG1','_RFSEAT2']
missing_99900_columns = ['MAXVO21_', 'FC601_', '_DRNKWK2']
missing_900_columns = ['DROCDY4_']

df_filter = df_filter.copy()
df_filter.loc[:, missing_9_columns] = df_filter.loc[:, missing_9_columns].replace(9, np.nan)
df_filter.loc[:, missing_99900_columns] = df_filter.loc[:, missing_99900_columns].replace(99900, np.nan)
df_filter.loc[:, missing_900_columns] = df_filter.loc[:, missing_900_columns].replace(900, np.nan)

df_filter = df_filter[df_filter['_MICHD'].notna()] #drop rows where heart disease state is missing

In [57]:
df_filter2 = df_filter.drop(columns=['_MICHD']) #drop the target variable

#drop columns with NA values > 25%
df_filter2 = df_filter2.dropna(thresh=len(df_filter)*0.75, axis=1)

In [58]:
#Filter out highly correlated features

def GetHighlyCorrelatedPairs(df, threshold):
    correlation_matrix = df.corr().abs()  # Compute the absolute correlation matrix
    # Mask the diagonal and lower triangle
    upper = correlation_matrix.where(np.triu(np.ones(correlation_matrix.shape), k=1).astype(bool))
    # Find pairs with correlation above the threshold
    highly_correlated_pairs = [(column, row, upper[column][row]) 
                               for column in upper.columns 
                               for row in upper.index 
                               if not pd.isna(upper[column][row]) and upper[column][row] > threshold]
    # Sort pairs by correlation value
    highly_correlated_pairs.sort(key=lambda x: x[2], reverse=True)
    return highly_correlated_pairs

# Example usage
highly_correlated = GetHighlyCorrelatedPairs(df_filter2, 0.75)
for pair in highly_correlated:
    print(f"Features {pair[0]} and {pair[1]} have a correlation of {pair[2]:.2f}")

def RemoveHighlyCorrelatedFeatures(df, threshold):
    correlation_matrix = df.corr().abs()
    upper = correlation_matrix.where(np.triu(np.ones(correlation_matrix.shape), k=1).astype(np.bool))
    to_drop = [column for column in upper.columns if any(upper[column] > threshold)]
    print('dropping columns:', to_drop) 
    return to_drop

df_filter2 = df_filter2.drop(columns=RemoveHighlyCorrelatedFeatures(df_filter2, 0.81))


Features FC601_ and MAXVO21_ have a correlation of 1.00
Features _PA300R4 and _PACAT3 have a correlation of 0.98
Features _AGE80 and FC601_ have a correlation of 0.97
Features _AGE80 and MAXVO21_ have a correlation of 0.97
Features _PA150R4 and _PACAT3 have a correlation of 0.96
Features _ASTHMS1 and _LTASTH1 have a correlation of 0.96
Features _PA150R4 and _PAINDX3 have a correlation of 0.96
Features _ASTHMS1 and _CASTHM1 have a correlation of 0.95
Features _PAINDX3 and _PACAT3 have a correlation of 0.95
Features _PA150R4 and _TOTINDA have a correlation of 0.94
Features _PA300R4 and _PA150R4 have a correlation of 0.92
Features _PAREC3 and _PAINDX3 have a correlation of 0.91
Features _PA30023 and _PA300R4 have a correlation of 0.90
Features _PAREC3 and _PA150R4 have a correlation of 0.89
Features _PA300R4 and _TOTINDA have a correlation of 0.88
Features _PAREC3 and _PACAT3 have a correlation of 0.88
Features _PACAT3 and _TOTINDA have a correlation of 0.88
Features _PA30023 and _PACAT3 

In [59]:
#impute missing values with the the median of the column (will only inpute columns with less than a threshold of missing values)
def GetColumnsToImpute(df_filter2, thresh):
    columns_to_impute = []

    for column in df_filter2.columns:
        if (df_filter2[column].isna().sum()/433323) < thresh:
            columns_to_impute.append(column)
    return columns_to_impute

columns_to_impute = GetColumnsToImpute(df_filter2, 0.15) #IF COLUMN MISSING VAL IS < 15% THEN IMPUTE

df_filter2 = df_filter2.copy()
for column in columns_to_impute:
    df_filter2[column].fillna(df_filter2[column].median(), inplace=True)

/var/folders/z7/2__sng712j3bvbdc64_2jnpr0000gn/T/ipykernel_25645/1446275049.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_filter2[column].fillna(df_filter2[column].median(), inplace=True)
/var/folders/z7/2__sng712j3bvbdc64_2jnpr0000gn/T/ipykernel_25645/1446275049.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we a

In [60]:
df_clean = df_filter2.dropna()

In [61]:
indices = df_clean.index
target = df_filter['_MICHD'].loc[indices]

In [62]:
target.replace(2, 0, inplace=True) #replace 2 with 0

In [63]:
X = df_clean
y = target
print(X.shape, y.shape)

(293509, 26) (293509,)


In [64]:
y.value_counts()

_MICHD
0.0    268757
1.0     24752
Name: count, dtype: int64

In [65]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score
from sklearn.preprocessing import StandardScaler
from xgboost import XGBRFClassifier
from imblearn.over_sampling import SMOTE

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

smote = SMOTE(random_state=42)
X_train, y_train = smote.fit_resample(X_train, y_train)
print("After SMOTE:", X_train.shape, y_train.shape)


After SMOTE: (376260, 26) (376260,)


# MODEL TRAINING 

In [66]:
from sklearn.metrics import accuracy_score, f1_score
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold, cross_val_score

def Get_accuracy_f1(pred, y_test):
    accuracy = accuracy_score(y_test, pred)
    f1 = f1_score(y_test, pred)
    return accuracy, f1

def EvaluatePredictions(predictions, y_test, model, train_X):
    accuracy, f1 = Get_accuracy_f1(predictions, y_test)
    stratified_cv = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)
    cv_scores = cross_val_score(model, train_X, y_train, cv=stratified_cv, scoring='f1')
    confusion = confusion_matrix(y_test, predictions)
    print('accuracy and f1 on test set', accuracy, f1)
    print("Stratified F1 Scores for each fold:", cv_scores)
    print("Mean F1 Score:", cv_scores.mean())
    print(confusion)
    

In [67]:
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

model_logistic = LogisticRegression(max_iter=1000, C=0.001, penalty='l2',solver='saga',class_weight='balanced')  
model_logistic.fit(X_train, y_train)
y_pred = model_logistic.predict(X_test)

EvaluatePredictions(y_pred, y_test, model_logistic, X_train)


accuracy and f1 on test set 0.7408606180368642 0.33876202619682394
Stratified F1 Scores for each fold: [0.77900438 0.77996048 0.77667848]
Mean F1 Score: 0.7785477804736011
[[59390 21237]
 [ 1581  5845]]


In [68]:
model = XGBRFClassifier(
    n_estimators=500,
    learning_rate=0.01,
    max_depth=5,
    random_state=42,
    eval_metric='logloss'
    
)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

EvaluatePredictions(y_pred, y_test, model, X_train)

accuracy and f1 on test set 0.7330471420621671 0.32263270128522853
Stratified F1 Scores for each fold: [0.80458101 0.80452359 0.8032031 ]
Mean F1 Score: 0.804102566312431
[[58949 21678]
 [ 1828  5598]]


In [69]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(n_estimators=200, max_depth=2, random_state=0,class_weight='balanced')
rf_model.fit(X_train, y_train)
y_pred = rf_model.predict(X_test)

EvaluatePredictions(y_pred, y_test, rf_model, X_train)


accuracy and f1 on test set 0.7176132556528454 0.31348187415444934
Stratified F1 Scores for each fold: [0.78642954 0.78445304 0.78584298]
Mean F1 Score: 0.7855751857452266
[[57511 23116]
 [ 1749  5677]]
