In [53]:
import numpy as np
import pandas as pd


# EDA, cleaning

In [1]:
df = pd.read_csv('LLCP2023.csv')

_STATE  FMONTH     IDATE  IMONTH  IDAY  IYEAR  DISPCODE       SEQNO  \
0          1.0     1.0   3012023       3     1   2023    1100.0  2023000001   
1          1.0     1.0   1062023       1     6   2023    1100.0  2023000002   
2          1.0     1.0   3082023       3     8   2023    1100.0  2023000003   
3          1.0     1.0   3062023       3     6   2023    1100.0  2023000004   
4          1.0     1.0   1062023       1     6   2023    1100.0  2023000005   
...        ...     ...       ...     ...   ...    ...       ...         ...   
433318    78.0    12.0  12112023      12    11   2023    1100.0  2023002064   
433319    78.0    12.0   1032024       1     3   2024    1100.0  2023002065   
433320    78.0    12.0  12132023      12    13   2023    1100.0  2023002066   
433321    78.0    12.0  12082023      12     8   2023    1100.0  2023002067   
433322    78.0    12.0  12112023      12    11   2023    1100.0  2023002068   

                _PSU  CTELENM1  ...      DROCDY4_  _RFBING6      _DRNKWK2  \
0       2.023000e+09       1.0  ...  5.397605e-79       1.0  5.397605e-79   
1       2.023000e+09       1.0  ...  5.397605e-79       1.0  5.397605e-79   
2       2.023000e+09       1.0  ...  5.397605e-79       1.0  5.397605e-79   
3       2.023000e+09       1.0  ...  5.397605e-79       1.0  5.397605e-79   
4       2.023000e+09       1.0  ...  7.000000e+00       1.0  4.700000e+01   
...              ...       ...  ...           ...       ...           ...   
433318  2.023002e+09       NaN  ...  7.100000e+01       2.0  1.500000e+03   
433319  2.023002e+09       NaN  ...  5.397605e-79       1.0  5.397605e-79   
433320  2.023002e+09       NaN  ...  3.000000e+00       1.0  4.700000e+01   
433321  2.023002e+09       NaN  ...  5.397605e-79       1.0  5.397605e-79   
433322  2.023002e+09       NaN  ...  6.700000e+01       2.0  9.330000e+02   

        _RFDRHV8  _FLSHOT7  _PNEUMO3  _AIDTST4  _RFSEAT2  _RFSEAT3  _DRNKDRV  
0            1.0       2.0       2.0       2.0       1.0       1.0       9.0  
1            1.0       1.0       1.0       2.0       1.0       1.0       9.0  
2            1.0       1.0       1.0       2.0       1.0       1.0       9.0  
3            1.0       1.0       1.0       1.0       1.0       1.0       9.0  
4            1.0       2.0       1.0       2.0       1.0       1.0       2.0  
...          ...       ...       ...       ...       ...       ...       ...  
433318       2.0       2.0       2.0       1.0       1.0       2.0       2.0  
433319       1.0       NaN       NaN       1.0       1.0       1.0       9.0  
433320       1.0       NaN       NaN       1.0       1.0       1.0       2.0  
433321       1.0       2.0       2.0       2.0       1.0       1.0       9.0  
433322       1.0       NaN       NaN       2.0       1.0       2.0       2.0  

[433323 rows x 350 columns]

In [159]:
df = df.loc[:,'_RFHLTH':] #only keep the 76 calculated variables

In [43]:
df['_RFSMOK3'].astype(str).str.count('9').sum()/433323

np.float64(0.053221269122571385)

In [62]:
df['METVL22_'].isna().sum()/433323

np.float64(0.47208664206608003)

In [160]:
columns_to_keep = ['_RFHLTH', '_PHYS14D', '_MENT14D', '_HLTHPL1', '_TOTINDA','METVL12_','MAXVO21_', 'FC601_','ACTIN13_','PADUR1_' ,'PAFREQ1_','_MINAC12','STRFREQ_','PAVIG13_', 'PA3MIN_','_PACAT3','_PAINDX3','_PA150R4', '_PA300R4', '_PA30023', '_PASTRNG', '_PAREC3', '_PASTAE3', '_RFHYPE6', '_CHOLCH3', '_RFCHOL3', '_MICHD', '_LTASTH1', '_CASTHM1', '_ASTHMS1', '_DRDXAR2', '_SEX', '_AGE80',   '_BMI5', '_RFBMI5', '_INCOMG1','_RACE', '_EDUCAG','_SMOKER3', '_RFSMOK3', '_CURECI2', 'DROCDY4_', '_RFBING6', '_RFSEAT2','_DRNKWK2']
df_filter = df[columns_to_keep]

missing_9_columns = ['_RFHLTH', '_PHYS14D', '_MENT14D', '_HLTHPL1', '_TOTINDA', '_PACAT3', '_PA150R4', '_PA300R4', '_PA30023', '_PASTRNG', '_PAREC3', '_PASTAE3', '_RFHYPE6', '_CHOLCH3', '_RFCHOL3', '_LTASTH1', '_CASTHM1', '_ASTHMS1', '_RFBMI5', '_RACE', '_SMOKER3', '_RFSMOK3', '_CURECI2', '_RFBING6','_PAINDX3','_EDUCAG','_INCOMG1','_RFSEAT2']
missing_99900_columns = ['MAXVO21_', 'FC601_', '_DRNKWK2']
missing_900_columns = ['DROCDY4_']

df_filter = df_filter.copy()
df_filter.loc[:, missing_9_columns] = df_filter.loc[:, missing_9_columns].replace(9, np.nan)
df_filter.loc[:, missing_99900_columns] = df_filter.loc[:, missing_99900_columns].replace(99900, np.nan)
df_filter.loc[:, missing_900_columns] = df_filter.loc[:, missing_900_columns].replace(900, np.nan)

df_filter = df_filter[df_filter['_MICHD'].notna()] #drop rows where heart disease state is missing

In [162]:
df_filter2 = df_filter.drop(columns=['_MICHD']) #drop the target variable

#drop columns with NA values > 25%
df_filter2 = df_filter2.dropna(thresh=len(df_filter)*0.75, axis=1)

In [164]:
columns_to_impute = []

for column in df_filter2.columns:
    if (df_filter2[column].isna().sum()/433323) < 0.1:
        columns_to_impute.append(column)

df_filter2 = df_filter2.copy()
for column in columns_to_impute:
    df_filter2[column].fillna(df_filter2[column].mode()[0], inplace=True)

In [167]:
df_clean = df_filter2.dropna()

In [169]:
indices = df_clean.index
target = df_filter['_MICHD'].loc[indices]

In [172]:
target.replace(2, 0, inplace=True) #replace 2 with

In [175]:
X = df_clean
y = target
print(X.shape, y.shape)

(244571, 37) (244571,)


In [176]:
y.value_counts()

_MICHD
0.0    222457
1.0     22114
Name: count, dtype: int64

In [210]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score
from sklearn.preprocessing import StandardScaler
from xgboost import XGBRFClassifier
from imblearn.over_sampling import SMOTE

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

smote = SMOTE(random_state=42)
X_train, y_train = smote.fit_resample(X_train, y_train)
print("After SMOTE:", X_train.shape, y_train.shape)


After SMOTE: (311438, 37) (311438,)


# MODEL TRAINING 

In [191]:
from sklearn.metrics import accuracy_score, f1_score
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold, cross_val_score

def Get_accuracy_f1(pred, y_test):
    accuracy = accuracy_score(y_test, pred)
    f1 = f1_score(y_test, pred)
    return accuracy, f1

def EvaluatePredictions(predictions, y_test, model, train_X):
    accuracy, f1 = Get_accuracy_f1(predictions, y_test)
    stratified_cv = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)
    cv_scores = cross_val_score(model, train_X, y_train, cv=stratified_cv, scoring='f1')
    confusion = confusion_matrix(y_test, predictions)
    print('accuracy and f1 on test set', accuracy, f1)
    print("F1 Scores for each fold:", cv_scores)
    print("Mean F1 Score:", cv_scores.mean())
    print(confusion)
    

In [194]:
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

model_logistic = LogisticRegression(max_iter=1000, C=0.001, penalty='l2',solver='saga',class_weight='balanced')  
model_logistic.fit(X_train, y_train)
y_pred = model_logistic.predict(X_test)

EvaluatePredictions(y_pred, y_test, model_logistic, X_train)


accuracy and f1 on test set 0.7322002943902306 0.34435583436217426
F1 Scores for each fold: [0.34606894 0.34378889 0.34916034]
Mean F1 Score: 0.3463393909957139
[[48563 18175]
 [ 1474  5160]]


In [208]:
model = XGBRFClassifier(
    n_estimators=500,
    learning_rate=0.01,
    max_depth=5,
    random_state=42,
    eval_metric='logloss'
    
)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

EvaluatePredictions(y_pred, y_test, model, X_train)

accuracy and f1 on test set 0.7558101499762852 0.3338315672058003
F1 Scores for each fold: [0.806248   0.80672905 0.80702392]
Mean F1 Score: 0.8066669911513795
[[84943 26286]
 [ 3575  7482]]


In [211]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(n_estimators=200, max_depth=2, random_state=0,class_weight='balanced')
rf_model.fit(X_train, y_train)
y_pred = rf_model.predict(X_test)

EvaluatePredictions(y_pred, y_test, rf_model, X_train)


accuracy and f1 on test set 0.6694651910810664 0.30077269057778805
F1 Scores for each fold: [0.78265117 0.78237918 0.78156288]
Mean F1 Score: 0.7821977442296385
[[43904 22834]
 [ 1418  5216]]


In [212]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(n_estimators=400, max_depth=3, random_state=0,class_weight='balanced')
rf_model.fit(X_train, y_train)
y_pred = rf_model.predict(X_test)

EvaluatePredictions(y_pred, y_test, rf_model, X_train)

accuracy and f1 on test set 0.6953061113231206 0.31766573068001464
F1 Scores for each fold: [0.80097646 0.80039293 0.79924542]
Mean F1 Score: 0.8002049358475816
[[45812 20926]
 [ 1430  5204]]
